[build-system]
requires = ["setuptools>=42", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "breezeml"
version = "0.1.2"
authors = [
  { name="Akash Anipakalu Giridhar", email="akash@example.com" }
]
description = "ðŸŒ¬ï¸ BreezeML ðŸ”¥âœ¨ â€” A beginner-friendly machine learning library built on scikit-learn."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
  "pandas",
  "numpy",
  "scikit-learn",
  "joblib"
]
keywords = ["machine learning", "education", "scikit-learn", "beginner"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Intended Audience :: Education"
]

[project.urls]
Homepage = "https://github.com/venomez-viper/breezeml"
Repository = "https://github.com/venomez-viper/breezeml"
Issues = "https://github.com/venomez-viper/breezeml/issues"
Documentation = "https://pypi.org/project/breezeml/"
